# Generated by Django 4.0.1 on 2024-02-27 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Status', models.CharField(default='', max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Photo1', models.CharField(max_length=100)),
                ('Photo2', models.CharField(max_length=100)),
                ('Photo3', models.CharField(max_length=100)),
                ('Aboutcompany', models.CharField(max_length=300)),
                ('registration_date', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Photo1', models.CharField(max_length=100)),
                ('Photo2', models.CharField(max_length=100)),
                ('Photo3', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Adharnumber', models.CharField(max_length=100)),
                ('Jobtype', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('post', models.CharField(default=0, max_length=100)),
                ('district', models.CharField(default=0, max_length=100)),
                ('state', models.CharField(default=0, max_length=100)),
                ('registration_date', models.CharField(default='', max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=100)),
                ('projectdescription', models.CharField(max_length=100)),
                ('projectlocation', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('no_of_workers', models.CharField(default='', max_length=100)),
                ('EMPLOYER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Previousworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo1', models.CharField(max_length=100)),
                ('Photo2', models.CharField(max_length=100)),
                ('Photo3', models.CharField(max_length=100)),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('FEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.fee')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login')),
            ],
        ),
        migrations.CreateModel(
            name='Jobvaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobfield', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('enddate', models.CharField(max_length=100)),
                ('eno_of_vaccancy', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('EMPLOYER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.employer')),
                ('PROJECT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.projects')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login'),
        ),
    ]
