# Generated by Django 4.0.1 on 2024-04-07 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Status', models.CharField(default='', max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('Photo1', models.CharField(max_length=100)),
                ('Photo2', models.CharField(max_length=100)),
                ('Photo3', models.CharField(max_length=100)),
                ('Aboutcompany', models.CharField(max_length=300)),
                ('registration_date', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=300)),
                ('Date', models.DateField()),
                ('Status', models.CharField(default='', max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=100)),
                ('projectdescription', models.CharField(max_length=100)),
                ('projectlocation', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('no_of_workers', models.CharField(default='', max_length=100)),
                ('EMPLOYER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Photo1', models.CharField(max_length=100)),
                ('Photo2', models.CharField(max_length=100)),
                ('Photo3', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Adharnumber', models.CharField(max_length=100)),
                ('Jobtype', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('post', models.CharField(default=0, max_length=100)),
                ('district', models.CharField(default=0, max_length=100)),
                ('state', models.CharField(default=0, max_length=100)),
                ('registration_date', models.CharField(default='', max_length=100)),
                ('lattitude', models.CharField(default=0, max_length=100)),
                ('longitude', models.CharField(default=0, max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login')),
            ],
        ),
        migrations.CreateModel(
            name='Workerrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.projects')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('FROMID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='WorkforceManagementSystem.login')),
                ('TOID', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='WorkforceManagementSystem.login')),
            ],
        ),
        migrations.CreateModel(
            name='Previousworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo1', models.CharField(max_length=100)),
                ('Photo2', models.CharField(max_length=100)),
                ('Photo3', models.CharField(max_length=100)),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('FEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.fee')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login')),
            ],
        ),
        migrations.CreateModel(
            name='Jobvaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobfield', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('enddate', models.CharField(max_length=100)),
                ('eno_of_vaccancy', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('salary', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('EMPLOYER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.employer')),
                ('PROJECT', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Jobrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('assigneddate', models.CharField(default=' ', max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('JOBVACANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.jobvaccancy')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.worker')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.CharField(default=0, max_length=100)),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frm_id', to='WorkforceManagementSystem.login')),
                ('TOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_id', to='WorkforceManagementSystem.login')),
            ],
        ),
        migrations.CreateModel(
            name='Assignproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('JOBREQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.jobrequest')),
                ('PROJECT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.projects')),
            ],
        ),
    ]
