# Generated by Django 4.0.1 on 2024-02-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Adharnumber', models.CharField(max_length=100)),
                ('Jobfield', models.CharField(max_length=100)),
                ('Jobtype', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=100)),
                ('Nationality', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Cv', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login')),
            ],
        ),
        migrations.CreateModel(
            name='Previousworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo1', models.CharField(max_length=100)),
                ('Photo2', models.CharField(max_length=100)),
                ('Photo3', models.CharField(max_length=100)),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('FEE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.fee')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login')),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Compantname', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Photo', models.CharField(max_length=100)),
                ('Date', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Website', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.login')),
            ],
        ),
    ]
