# Generated by Django 4.0.1 on 2024-03-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='lattitude',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='longitude',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
