# Generated by Django 4.0.1 on 2024-04-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='projectstartdate',
        ),
    ]
