# Generated by Django 4.0.1 on 2024-02-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='Compantname',
            new_name='Companyname',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='Username',
            new_name='Companysize',
        ),
        migrations.AddField(
            model_name='employer',
            name='Aboutcompany',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='Photo1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='Photo2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='Photo3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
