# Generated by Django 4.0.1 on 2024-02-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0002_rename_compantname_employer_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
