# Generated by Django 4.0.1 on 2024-04-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0002_remove_projects_projectstartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
