# Generated by Django 4.0.1 on 2024-03-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0002_worker_lattitude_worker_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobvaccancy',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='jobvaccancy',
            name='salary',
            field=models.CharField(default='', max_length=100),
        ),
    ]
