# Generated by Django 4.0.1 on 2024-03-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0003_jobvaccancy_district_jobvaccancy_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('JOBVACANCY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.jobvaccancy')),
                ('WORKER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.worker')),
            ],
        ),
    ]
