# Generated by Django 4.0.1 on 2024-02-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0003_employer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='Companysize',
        ),
    ]
