# Generated by Django 4.0.1 on 2024-02-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0004_remove_employer_companysize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='Age',
            new_name='Photo1',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Address',
            new_name='Photo2',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Cv',
            new_name='Photo3',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Jobfield',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='worker',
            name='district',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='post',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='state',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
