# Generated by Django 4.0.1 on 2024-03-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0005_workerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerrequest',
            name='EMPLOYER',
        ),
        migrations.AddField(
            model_name='workerrequest',
            name='PROJECT',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.projects'),
            preserve_default=False,
        ),
    ]
