# Generated by Django 4.0.1 on 2024-02-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0005_rename_age_worker_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='rejistration_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='rejistration_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
