# Generated by Django 4.0.1 on 2024-02-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0006_employer_rejistration_date_worker_rejistration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employer',
            old_name='rejistration_date',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='rejistration_date',
            new_name='registration_date',
        ),
    ]
