# Generated by Django 4.0.1 on 2024-02-21 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0007_rename_rejistration_date_employer_registration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projecttitle', models.CharField(max_length=100)),
                ('projectdescription', models.CharField(max_length=100)),
                ('projectlocation', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('EMPLOYER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkforceManagementSystem.employer')),
            ],
        ),
    ]
