# Generated by Django 4.0.1 on 2024-03-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0007_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('FROMID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr_id', to='WorkforceManagementSystem.login')),
            ],
        ),
    ]
