# Generated by Django 4.0.1 on 2024-02-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0008_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='no_of_workers',
            field=models.CharField(default='', max_length=100),
        ),
    ]
