# Generated by Django 4.0.1 on 2024-03-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0008_groupchat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groupchat',
        ),
    ]
