# Generated by Django 4.0.1 on 2024-02-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0009_projects_no_of_workers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobvaccancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('jobfield', models.CharField(max_length=100)),
                ('companyname', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('startdate', models.CharField(max_length=100)),
                ('enddate', models.CharField(max_length=100)),
                ('eno_of_vaccancy', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
            ],
        ),
    ]
