# Generated by Django 4.0.1 on 2024-02-23 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0011_jobvaccancy_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvaccancy',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='jobvaccancy',
            name='companyname',
        ),
        migrations.RemoveField(
            model_name='jobvaccancy',
            name='email_id',
        ),
    ]
