# Generated by Django 4.0.1 on 2024-03-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0011_notifications_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
