# Generated by Django 4.0.1 on 2024-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0013_assignproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='assigneddate',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
