# Generated by Django 4.0.1 on 2024-03-28 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0014_jobrequest_assigneddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('rating', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='WorkforceManagementSystem.login')),
                ('to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='WorkforceManagementSystem.login')),
            ],
        ),
    ]
