# Generated by Django 4.0.1 on 2024-03-28 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkforceManagementSystem', '0015_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='to_id',
        ),
        migrations.AddField(
            model_name='review',
            name='EMPLOYER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='WorkforceManagementSystem.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='WORKER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='toid', to='WorkforceManagementSystem.worker'),
            preserve_default=False,
        ),
    ]
